version: 2
sources:
  - name: strava_data
    tables:
      - name: strava_activities
        config:
          external_location: "/Users/mathieulinel/Documents/perso/Road to 70_3/road_to_70_3/data/strava_data.duckdb"