version: 2
sources:
  - name: strava_raw
    schema: raw
    tables:
      - name: strava_activities
        description: "Strava activities data"
        columns:
        - name: id
          description: "Activity ID"
          tests:
            - unique
            - not_null