
version: 2

models:
  - name: stg__strava_activities
    description: "Transformations for Strava activities data"
    columns:
      - name: id
        description: "Activity ID"
        data_tests:
          - unique
          - not_null