
version: 2

models:
  - name: sandbox
    # description: "Sandbox for testing"
    # columns:
    #   - name: *
    #     description: "All columns"
    #     data_tests:
    #       - unique
    #       - not_null